// PLACES ACTIONS
export const ADD_PLACE = "ADD_PLACE";
export const DELETE_PLACE = "DELETE_PLACE";

// USER ACTIONS
export const TRY_AUTH = "TRY_AUTH";

// UI LOADER
export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";
